dist: xenial
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install pipenv --upgrade-strategy=only-if-needed
  - pipenv install
  - python3 setup.py install
script:
  - cd tests
  - python3 data-tests.py
